test:
  services:
    - mysql:5.7
  variables:
    MYSQL_DATABASE: dbconnect_test
    MYSQL_ROOT_PASSWORD: mysqlpass
    CI_ENV: Gitlab
  script:
    - apt-get update -qy
    - apt-get install -y python3-dev python3-pip mysql-client default-libmysqlclient-dev
    - pip3 install -r requirements.txt
    - pip3 install mysqlclient
    - "./test/mysql-ci-setup -hmysql -uroot -pmysqlpass"
    - python3 tests.py
