dist: trusty
sudo: required
language: python
addons:
  apt:
    packages:
      - python3-mysql.connector
      - python-mysql.connector
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
python:
  - "2.7"
  - "3.5"
  - "pypy"
  - "pypy3"
services:
  - mysql
install:
  - pip install -r requirements.txt
before_script:
  - "./travis-ci-setup -h127.0.0.1 -uroot"
virtualenv:
  system_site_packages: true
script: python tests.py
notifications:
  irc:
    channels: "irc.mozilla.org#dbConnect"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
