dist: trusty
sudo: required
language: python
addons:
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
python:
  - "2.7"
  - "3.6"
services:
  - mysql
install:
  - pip install -r requirements.txt
  - pip install mysqlclient
before_script:
  - "./test/mysql-ci-setup -h127.0.0.1 -uroot"
virtualenv:
  system_site_packages: true
script: python tests.py
notifications:
  irc:
    channels: "irc.freenode.org#dbConnect"
    template:
      - "%{repository}@%{branch}: %{message} (%{build_url})"
    on_success: change
    on_failure: change
